import {SCHENGEN_COUNTRY_SLUGS} from './countries'

// Ordinary-passport short-stay Schengen visa exemptions. Special passports,
// residence permits, family-member routes, suspensions, and bilateral rules can
// change the answer, so UI copy still points users to official sources.
export const VISA_EXEMPT_NATIONALITY_SLUGS = new Set([
  ...SCHENGEN_COUNTRY_SLUGS,
  'albania',
  'andorra',
  'antigua-and-barbuda',
  'argentina',
  'australia',
  'bahamas',
  'barbados',
  'bosnia-and-herzegovina',
  'brazil',
  'brunei',
  'canada',
  'chile',
  'colombia',
  'costa-rica',
  'cyprus',
  'dominica',
  'el-salvador',
  'georgia',
  'grenada',
  'guatemala',
  'honduras',
  'hong-kong',
  'ireland',
  'israel',
  'japan',
  'kiribati',
  'kosovo',
  'macao',
  'malaysia',
  'marshall-islands',
  'mauritius',
  'mexico',
  'micronesia',
  'moldova',
  'monaco',
  'montenegro',
  'new-zealand',
  'nicaragua',
  'north-macedonia',
  'palau',
  'panama',
  'paraguay',
  'peru',
  'saint-kitts-and-nevis',
  'saint-lucia',
  'saint-vincent-and-the-grenadines',
  'samoa',
  'san-marino',
  'serbia',
  'seychelles',
  'singapore',
  'solomon-islands',
  'south-korea',
  'taiwan',
  'timor-leste',
  'tonga',
  'trinidad-and-tobago',
  'tuvalu',
  'ukraine',
  'united-arab-emirates',
  'united-kingdom',
  'united-states',
  'uruguay',
  'vatican-city',
  'venezuela',
])

export function needsShortStaySchengenVisa(nationalitySlug) {
  return !VISA_EXEMPT_NATIONALITY_SLUGS.has(nationalitySlug)
}
